### ISSUE TITLE
useGeolocation: Check for `navigator.geolocation` before attempting to use it

### ISSUE THREAD

**Issue by brandoningli** [childrentime/reactuse#100]
We're running into an issue where a small subset of users using an old browser are having their page crash when the `useGeolocation` hook runs due to `navigator.geolocation` not being defined.

Please add in a check to make sure this is defined and only run the `navigator.geolocation` functions should they actually exist on the navigator object.

**Comment by childrentime** [comment]
Thanks. I will fix it.

**Comment by childrentime** [comment]
@brandoningli try v5.0.18

**Comment by brandoningli** [comment]
Looks great! Thanks for the quick turnaround!
