### ISSUE TITLE
[Bug] useEventSource中的error错误触发

### ISSUE THREAD

**Issue by CNFeffery** [childrentime/reactuse#108]
对于`sse`服务的正常响应结束（譬如大语言模型服务回复完成），`useEventSource`的`error`会在响应结束时被多余的更新一次

**Comment by childrentime** [comment]
可以给一个复现的链接么，理论上来说只有 onerror事件触发的时候会更新

**Comment by CNFeffery** [comment]
@childrentime 😰不太好举在线的例子，因为需要调用一个类似LLM服务的，有限输出后结束的`sse`请求，我看官网上的示例服务`https://sse.dev/test`是一直在通信的

**Comment by CNFeffery** [comment]
譬如我这边本地调用的`sse`接口，在返回几次内容后就结束请求过程了：
![image](https://github.com/user-attachments/assets/c7e91988-0649-4c23-bb73-c097602b1067)

但是针对这种正常的响应结束，`error`还是被更新了：
![image](https://github.com/user-attachments/assets/b8509ff6-68b6-44ae-b507-fa59c6ab97f8)

如果有办法能在`error`中体现出错误原因等信息，应该可以甄别是错误还是正常的响应结束

**Comment by childrentime** [comment]
我研究一下

**Comment by childrentime** [comment]
https://stackoverflow.com/questions/6534572/how-to-close-a-server-sent-events-connection-on-the-server

**Comment by childrentime** [comment]
在服务器关闭链接之后，触发onError事件是chrome的默认行为，没有什么方法来分辨是服务器关闭导致的 error 还是 client side的 error，因此，你可能需要你的sse接口在数据末尾发送一个关闭sse的消息，显式调用 close 方法来关闭。

**Comment by childrentime** [comment]
<img width="590" alt="image" src="https://github.com/user-attachments/assets/70760c35-38c4-44d7-90db-ddfc8716db47">
<img width="876" alt="image" src="https://github.com/user-attachments/assets/fd16088a-30cf-46a8-ae18-e387b398a031">
大模型相关的api接口，一般来说都应该有 isFinal这样的消息

**Comment by CNFeffery** [comment]
@childrentime 好的谢谢🙏
