### ISSUE TITLE
useEventSource请求类型设置

### ISSUE THREAD

**Issue by CNFeffery** [childrentime/reactuse#112]
请问可以为`useEventSource`添加可选的`post`请求类型设置，并支持传递`payload`等常用参数的功能吗🙏

**Comment by CNFeffery** [comment]
譬如，智谱清言的大模型sse请求：
![image](https://github.com/user-attachments/assets/920a72e1-2c67-458d-90f1-e1d97731f38a)

**Comment by childrentime** [comment]
你有能直接 get/post请求调用的 sse接口么， 我想测试一下。

**Comment by childrentime** [comment]
#113   v5.0.23-beta.1 我发了一个beta版本，你可以先试试有没有问题。 https://deploy-preview-113--unrivaled-moxie-138fa2.netlify.app/browser/useFetchEventSource

**Comment by CNFeffery** [comment]
> #113 v5.0.23-beta.1 我发了一个beta版本，你可以先试试有没有问题。 https://deploy-preview-113--unrivaled-moxie-138fa2.netlify.app/browser/useFetchEventSource

好的👌谢谢大佬

**Comment by childrentime** [comment]
可以吗，没问题的话我就发个正式版本。

**Comment by CNFeffery** [comment]
> 可以吗，没问题的话我就发个正式版本。

我这边测试常规的没问题👌
