### ISSUE TITLE
[useTimeoutFn] immediate in the documentation is different from the code

### ISSUE THREAD

**Issue by nnecec** [childrentime/reactuse#119]
The default value for immediate in the documentation is false, but the default value in the code is true.

documentation: https://www.reactuse.com/effect/useTimeoutFn#usetimeoutfnoptions

code implementation: https://github.com/childrentime/reactuse/blob/main/packages/core/src/useTimeoutFn/index.ts#L20

**Comment by childrentime** [comment]
Sorry for that. Do you want to open a pr to fix docs? just modify the interface.ts near to index.ts

**Comment by nnecec** [comment]
Do we need to set the immediate default to true?

**Comment by childrentime** [comment]
Yeah
