### ISSUE TITLE
[v6] Breaking Change: Full ConcurrentMode Support & Unified Event Handler Code

### ISSUE THREAD

**Issue by childrentime** [childrentime/reactuse#121]
1. Ensure that each custom hook is concurrent-mode safe. This requires following certain principles, such as:
   - avoiding reading or writing refs during the render process.
2. When using external state management libraries, useSyncExternalStore must be used. However, this usually doesn't concern us as we generally don't store setState.
3. Given that stable event handler hooks would only have incorrect values when read within a child component's useLayoutEffect, I believe we can temporarily ignore this scenario and uniformly wrap translated event handlers with useEvent.
```tsx
function Example(props) {
  const callback = useDynamicCallback(props.callback);
  return <Child callback={callback} />;
}

function Child({ callback }) {
  useLayoutEffect(() => {
    // Child effects are run before parent effects!
    // This means the callback ref has not yet been updated-
    // which means that it still points to the previous version,
    // with stale values and potentially different behavior.
    // This function call will probably cause problems!
    callback();
  }, []);
}
``` 

references:
https://github.com/facebook/react/issues/16956#issuecomment-536636418
https://github.com/facebook/react/issues/18003#issuecomment-583875570

**Comment by childrentime** [comment]
he first step should be creating a v6 branch and cherry-picking the relevant previous commits into it.

**Comment by FleetAdmiralJakob** [comment]
Why not just make all hooks that are not compatible with concurrent mode yet compatible on top of the main branch and then releasing everything together as v6?

**Comment by childrentime** [comment]
It depends on the v5 version with any new features or modifications. I'm mainly still thinking about supporting concurrent mode, where else does our code need to be changed to support, and if there are not too many changes, there is no need to pull a v6 branch

**Comment by childrentime** [comment]
#125
