### ISSUE TITLE
选择文件时获取对应的绝对路径

### ISSUE THREAD

**Issue by CNFeffery** [childrentime/reactuse#124]
譬如针对[useFileDialog](https://www.reactuse.com/zh-Hans/browser/useFileDialog)，请问有方法可以实现选中文件后，获取到文件在设备上的绝对路径吗

举个例子  对于 https://github.dev/childrentime/reactuse ，其中打开本地文件的功能：

![image](https://github.com/user-attachments/assets/9e4a01d1-93d2-4847-9f55-eec96911b9c3)
![image](https://github.com/user-attachments/assets/2b519834-853e-478d-a7c0-0133172e8bf7)
![image](https://github.com/user-attachments/assets/9da170d3-6fe3-41c2-8094-868561b20dab)

**Comment by childrentime** [comment]
出于安全考虑,浏览器不允许直接获取用户选择文件的真实本地路径。当用户通过input[type="file"]选择文件时,浏览器只会提供一个虚拟的文件路径或blob URL,而不是实际的文件系统路径
