### ISSUE TITLE
useFetchEventSource功能异常

### ISSUE THREAD

**Issue by CNFeffery** [childrentime/reactuse#126]
以useFetchEventSource文档页示例sse服务为例，当正建立了sse请求处于通信中状态时，每次切到其他浏览器标签页再回来，都会触发多余的新的sse请求：

![demo](https://github.com/user-attachments/assets/dfd93caf-fd5b-4cc8-a405-f5ca1d785e5a)

**Comment by childrentime** [comment]
收到，等我回家了瞅瞅

**Comment by childrentime** [comment]
虽然我这没复现，但是你可以传递   openWhenHidden=false 选项试试

**Comment by CNFeffery** [comment]
> 虽然我这没复现，但是你可以传递 openWhenHidden=false 选项试试

我试了一下，`openWhenHidden`参数设置后没有变化，还是出现上面的重复创建新请求问题：
![image](https://github.com/user-attachments/assets/8d1f3dbb-fa1c-4e2c-b907-182f24b2d193)

**Comment by CNFeffery** [comment]
@childrentime 我创建了一个有效期几个月的公开流式服务，地址：https://broad-scene-1112.ploomberapp.io/stream

直接在在线文档网上粘贴这个服务地址就可以复现问题：

![demo](https://github.com/user-attachments/assets/d1d91ad2-8786-4500-8223-1830a9455f7a)

**Comment by childrentime** [comment]
fixed in v6.0.1, 我看了下主要是 openWhenHidden 选项被覆盖了之前

**Comment by CNFeffery** [comment]
@childrentime 我试了目前官网最新的基础使用例子（ https://www.reactuse.com/zh-Hans/browser/useFetchEventSource#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95 ），还存在每次切换回来后多余创建请求的情况😭

![image](https://github.com/user-attachments/assets/706841cc-079e-48bd-876c-acc776b54565)

**Comment by CNFeffery** [comment]
openWhenHidden设置为`true`就没这个问题了，感谢大佬🎉
