### ISSUE TITLE
group the code and tests inside the same folder for each function

### ISSUE THREAD

**Issue by Daydreamer-riri** [childrentime/reactuse#14]
Currently, the implementation and tests
 of the same function are stored in different folders, which makes the context of each function more scattered. 
If they are moved into the same folder, it can allow each function to be written without jumping between multiple folders.

New structures could be:
```
└──  useToggle
     ├── index.spec.ts
     └── index.ts
```

**Comment by childrentime** [comment]
OK. I am pleasure with it. just do it  with some scripts.

**Comment by childrentime** [comment]
If you want to deal with it, just assign it to yourself, otherwise I will handle it😘

**Comment by Daydreamer-riri** [comment]
Leave it to me
