### ISSUE TITLE
Switch the package manager to pnpm

### ISSUE THREAD

**Issue by Daydreamer-riri** [childrentime/reactuse#2]
Perhaps switching the package manager to pnpm could provide better monorepo support.

I am happy to commit a pull request to complete it.

**Comment by childrentime** [comment]
At present, I do not use monorepo, because it has some problems during importing resources to build document website with yarn. yarn link is used directly. But if you want to improve, just do it💘

**Comment by Daydreamer-riri** [comment]
Thank you for your reply. I will complete this PR as soon as possible.
