### ISSUE TITLE
Add useCookie And Export Size

### ISSUE THREAD

**Issue by childrentime** [childrentime/reactuse#21]
A. We can add a useCookie hook.

it looks like

```tsx
const [cookie,setCookie,removeCookie,refreshCookie] = useCookie(key,options,defaultValue)
```

* The options should take control of cookie attributes like `path`, `expires`.
* The defaultValue for the server side. Users should serialize the defaultValue on the server side and provide the same value in client side.
* When a user makes a network request, we may need to refresh the cookie

B. Like vueuse, we can add the volume size that each function exports. But I'm not sure where to display it on the website page, or just add it to the README file.

```ts
import path from "node:path";
import { getExportsSize } from "export-size";
import { filesize } from "filesize";
import fs from "fs-extra";

const exportSize = path.resolve(__dirname, "../export-size.json");
async function run() {
  const mdJSON = <{ [name: string]: string }>{};
  const { exports } = await getExportsSize({
    pkg: "./",
    output: false,
    bundler: "rollup",
    external: ["react"],
  });

  for (const exp of exports) {
    mdJSON[exp.name] = filesize(exp.minzipped, { base: 2, standard: "jedec" }) as string;
  }

  fs.writeJSON(exportSize, mdJSON, { spaces: 2 });
}

run();
```
@Daydreamer-riri what do you think?

**Comment by Daydreamer-riri** [comment]
Regarding B, I believe it should be displayed on the website and the README file should be fully written by the developer.

**Comment by childrentime** [comment]
yeah, I think I'll just generate some metadata directly with markdown-loader, I will handle this.

**Comment by Daydreamer-riri** [comment]
Do you think it's better to replace markdown-it with mdx? Markdown-it has a better ecosystem related to Vue, but I'm having trouble finding a way to import React components in mdit.
I can do this task and optimize the display effect of the document.

**Comment by childrentime** [comment]
Forget it🥹. Markdown it is good enough.

**Comment by childrentime** [comment]
> I can do this task and optimize the display effect of the document.

Alright🥳. Do you also want to add the useCookie hook?

**Comment by Daydreamer-riri** [comment]
Sure. And I will continue to learn Markdown-it

**Comment by Daydreamer-riri** [comment]
Hi, regarding useCookie, I currently have two implementations: one is based on js-cookie and requires importing this dependency; the other uses the experimental API cookieStore, but currently Firefox and Safari do not support it yet(see [cookieStore](https://caniuse.com/?search=cookieStore).

How do you think we should choose?

**Comment by childrentime** [comment]
Maybe we can load them separately in different environments？ Use `useIsSupported` to detect.

**Comment by Daydreamer-riri** [comment]
In this case, this dependency will still be imported (unless dynamic import is used)

I think just use js-cookie directly, it can cover all scenarios

**Comment by childrentime** [comment]
Alright.It's up to you😉
