### ISSUE TITLE
Migrate to vite

### ISSUE THREAD

**Issue by childrentime** [childrentime/reactuse#30]

**Comment by childrentime** [comment]
```
import path from "node:path";
import markdown from "../utils/markdown";
import { getMarkdownSection } from "../config/plugins/pre-markdown-loader";

const fileRegex = /\.md$/;

const pkg = "core";

export default async function pluginMD() {
  return {
    name: "plugin-markdown",

    async transform(src: string, id: string) {
      if (fileRegex.test(id)) {
        const index = id.lastIndexOf(path.sep);
        const prePath = id.slice(0, index);
        const name = prePath.slice(prePath.lastIndexOf(path.sep) + 1);

        const { typeDeclarations } = await getMarkdownSection(pkg, name);

        const demoPath = id.replace("README.md", "demo.tsx");
        const originHtml = markdown.render(src);

        const code = `
        import Demo from '${demoPath}';
        function Layout() (
          <div>
            <div dangerouslySetInnerHTML={{__html: ${originHtml}}} />
            <div>
              <h2>Example</h2>
              <div className="demo-container">
                <Demo />
              </div>
            </div>
            <div dangerouslySetInnerHTML={{__html: ${typeDeclarations}}} />
          </div>
        )
        export default Layout;
        `;

        return {
          code: JSON.stringify(code),
        };
      }
    },
  };
}
```

@Daydreamer-riri I am trying to write a vite plugin to handle the transfrom markdown to react component, do you know can vite support chain loaders like you wrote in webpack
```
 {
        test: /\.md$/,
        use: [
          {
            loader: "babel-loader",
            options: {
              caller: { target },
            },
          },
          {
            loader: path.resolve(__dirname, "./plugins/markdown-loader.ts"),
          },
          {
            loader: path.resolve(__dirname, "./plugins/pre-markdown-loader.ts"),
          },
        ],
      },
```
I try to pass it to @vitejs/plugin-react but it didn't work😡
Maybe I shold import babel to parse it? It sucks

**Comment by Daydreamer-riri** [comment]
The plugin scheduling of vite is the same as rollup, transform of each plugin will be called. Maybe you can check out whether your plugin is correctly called? Check what the code it receives

**Comment by Daydreamer-riri** [comment]
You can log in your transform function to see how it's being called.
At the same time, you can find the context of the plugin scheduling in the CreatepluginContainer function under the Plugincontainer file in the vite source code. Here you can log to check the entire process of a file. If the plugin does not work, it may also be related to the scheduling order.

**Comment by childrentime** [comment]
I pushed my current update in #34 🤓. I have read  the code of two repositories related to Markdown.
https://github.com/geekris1/vite-plugin-react-markdown/blob/master/src/markdown.ts. This one uses Babel to handle the transformed code after Markdown conversion.
https://github.com/mdx-js/mdx/blob/main/packages/rollup/lib/index.js. The compilation result for Markdown looks like this:
<img width="865" alt="image" src="https://github.com/childrentime/reactuse/assets/58261676/bdc8f94a-bce5-4a5d-b242-46e770580277">

**Comment by childrentime** [comment]
@Daydreamer-riri From what I can see, it may be necessary to manually add Babel because Markdown-it only performs the operation of converting the .md file into a string. We still need to convert the string into a JS module that Vite can understand. This is where Vite comes in, and we need to bundle all the logic into a single plugin

**Comment by childrentime** [comment]
Let's consider this as a draft for now. I found it challenging to migrate to Vite. On one hand, @loadable/component is not supported in Vite, and on the other hand, Vite's CSS injection in the SSR environment is not well supported. Perhaps these issues may not exist in the production environment, but for development purposes, it seems that CSR (Client-Side Rendering) is the better choice. However, I specifically need SSR in the development environment to catch errors in advance.

**Comment by Daydreamer-riri** [comment]
I'm starting to solve the problem about CSS.

**Comment by childrentime** [comment]
Thanks! I have gone through many Vite issues, but haven't been able to solve the problem effectively.

**Comment by childrentime** [comment]
@Daydreamer-riri  I fixed css by this.

```tsx
   const mod = await vite.moduleGraph.getModuleByUrl("/src/App.tsx") as ModuleNode;

      const cssUrls = new Set<string>();
      const collectCss = async (mod: ModuleNode) => {
        const deps = mod?.ssrTransformResult?.deps || [];
        for (const dep of deps) {
          if (dep.endsWith(".css")) {
            cssUrls.add(dep);
          }
          else if (dep.endsWith(".tsx")) {
            const depModule = await vite.moduleGraph.getModuleByUrl(dep);
            depModule && collectCss(depModule);
          }
        }
      };
      await collectCss(mod);

      const stylesTag = [...cssUrls]
        .map((url) => {
          return `<link rel="stylesheet" type="text/css" href="${url}">`;
        })
        .join("");
```

LGTM.
My mistake. I overlooked some things.

**Comment by Daydreamer-riri** [comment]
haha, I also did a similar implementation
```ts
export function getStylesTag(mod: ModuleNode | undefined) {
  const cssUrls = collectCss(mod);
  const result = [...cssUrls]
    .map(url => `<style type="text/css" vite-module-id="${hashCode(url)}" rel="stylesheet" href="${url}">`)
    .join("");
  return result;
}

export function collectCss(
  mod: ModuleNode | undefined,
  preloadUrls: Set<string> = new Set(),
  visitedModules: Set<string> = new Set(),
) {
  if (!mod)
    return preloadUrls;
  if (!mod.url)
    return preloadUrls;
  if (visitedModules.has(mod.url))
    return preloadUrls;
  visitedModules.add(mod.url);
  if (mod.url.endsWith(".css") || (mod.id && /\?vue&type=style/.test(mod.id))) {
    preloadUrls.add(mod.url);
  }
  mod.importedModules.forEach((dep) => {
    collectCss(dep, preloadUrls, visitedModules);
  });
  return preloadUrls;
}
```

**Comment by childrentime** [comment]
@Daydreamer-riri haha. There is one final problem remaining now, which is the dynamic loading of routing code. Are you willing to help me solve this issue? It is on here: https://github.com/childrentime/reactuse/pull/34/commits/023e9f19a60c0a63c188a95f676bf1872bc81e28#diff-206517f406f56092bcf162160d88cef1db3013adb482149ac09827d850ba4804R44-R61

**Comment by Daydreamer-riri** [comment]
Hi, I think we can solve this problem through `rendertopPipeablestream`.
It is an example that can work normally: [example](https://github.com/Daydreamer-riri/reactuse/commit/dc12df0bc95763db7e4863a872d2f42aa6a52c44), I think we can make improvements based on it

**Comment by childrentime** [comment]
@Daydreamer-riri Lazy and Suspence are good. But Can rendertopPipeablestream be used for SSG?

**Comment by Daydreamer-riri** [comment]
I don't know much about ssg.  I will look for some information to learn

**Comment by Daydreamer-riri** [comment]
I think SSG needs to write additional logic separately, and SSG does not need to streaming, so we don’t need to use the `renderToPipeableStream`

**Comment by childrentime** [comment]
I have not used renderToPipeableStream for SSG before, but suspense and renderToString will not work together . I will give it a try. Generally, this API requires a Node server.

**Comment by Daydreamer-riri** [comment]
I see in the [documentation](https://react.dev/reference/react-dom/server/renderToPipeableStream#returns) that `renderToPipeableStream` can be used for static generation with onAllReady option. Perhaps I can implement a library to do this

**Comment by childrentime** [comment]
I have doing this. Everything works fine except markdown handle by vite in production mode. I will push my code later at working time.

**Comment by Daydreamer-riri** [comment]
That's great~thanks for your work!

**Comment by childrentime** [comment]
We're almost done with all the work, just this last step remaining. Please review my latest [code](https://github.com/childrentime/reactuse/pull/34) and run `pnpm build` and `pnpm preview` locally to see the changes.

**Comment by childrentime** [comment]
Solved this. It seems like when you custom your build function, you don't need import your vite plugin again.

**Comment by childrentime** [comment]
@Daydreamer-riri  https://64ad08e0ad60ba00081e27f2--unrivaled-moxie-138fa2.netlify.app/. It totally works!!! Please help me review it for any issues. If there are no issues, we can proceed with merging it.

**Comment by childrentime** [comment]
Using Vite reduces the need for a bunch of configurations. Awesome!
