### ISSUE TITLE
usePermission doesn't work on Firefox

### ISSUE THREAD

**Issue by bfaulk96** [childrentime/reactuse#35]
When used on Chrome, `usePermission` works as expected, returning `prompt` when prompting and `granted` when approved.
When the same code is run in Firefox, however, the hook always returns an empty string.

Code example:
```typescript
const cameraPermission = usePermission('camera');
const micPermission = usePermission('microphone');
console.log(cameraPermission, micPermission);
```

**Comment by bfaulk96** [comment]
My bad, this is a non-issue. The problem is Chrome vs Firefox having different permission names that this supports, as defined [here](https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query#name)

**Comment by bfaulk96** [comment]
Upon further inspection, this still didn't work in Firefox for some reason, even using permissions that Firefox does support

**Comment by childrentime** [comment]
I'll check it later. Sorry it's saturday and I has to go out now.

**Comment by childrentime** [comment]
<img width="1052" alt="image" src="https://github.com/childrentime/reactuse/assets/58261676/8f6d22e8-3f80-4f6a-8705-a288b4a33736">
@bfaulk96 Hello, can you provide what permissionName do you use? It's seems to work fine.

**Comment by bfaulk96** [comment]
Hmm. I cannot reproduce my issue anymore either using supported permissions names. My apologies
