### ISSUE TITLE
Feature Request: Some way to refresh device list of `useMediaDevices`

### ISSUE THREAD

**Issue by bfaulk96** [childrentime/reactuse#40]
While working with some webcam flows in React, I've found that permissions states can be really funky in browsers. Specifically, when first requesting permissions, you don't have access to the proper input device list until the user has granted permissions. Once the user _does_ grant permissions, it doesn't seem to automatically re-trigger the `useMediaDevices` hook, since that's not directly tied to any permission change events (and can't effectively be since Firefox doesn't support `camera`/`microphone` as permissions in the permissions API).

My proposal:

Some sort of optional function that can be used to manually trigger an update on the useMediaDevices check, i.e.

```ts
const { devices, reload: reloadDeviceList } = useMediaDevices();
...
navigator.mediaDevices.getUserMedia({ audio: true, video: true }).then((stream) => {
      stream.getTracks().forEach((track) => track.stop());
      reloadDeviceList();
    })
```

**Comment by childrentime** [comment]
Thanks for report! I will git it a try soon.

**Comment by childrentime** [comment]
@bfaulk96 we support it in version 3.0.1 . We have made a breaking change to the return value of useMediaDevices by modifying it to be an array. Additionally, we have added a parameter to determine whether to request permission immediately.

**Comment by bfaulk96** [comment]
@childrentime Just checked it out, thanks! This is great! I did notice that when checking it out on the docs page, the first time you accept permissions, it looks like it doesn't properly close the stream; it stays trying to record until you refresh.

**Comment by childrentime** [comment]
oh, crap. I should not be hurry. I will recheck it.

**Comment by bfaulk96** [comment]
@childrentime our team just learned that Safari doesn't support `navigator!.permissions.query`... Not necessarily asking for Safari support on this, but it might be good to throw that in the isSupported check

**Comment by childrentime** [comment]
@bfaulk96 Hi, I want to know if it works correctly on Safari 15? If it does, It is just executing an additional unnecessary JavaScript code?

**Comment by childrentime** [comment]
I see it from https://caniuse.com/?search=permission.query

**Comment by childrentime** [comment]
if Safari 15 or below does not support this functionality at all, then i will add it to the useSupported check and return it.

**Comment by bfaulk96** [comment]
> if Safari 15 or below does not support this functionality at all, then i will add it to the useSupported check and return it.

Correct, it throws an error in the browser – `TypeError: undefined is not an object (evaluating 'navigator.permissions.query')`

**Comment by childrentime** [comment]
I want to know if it can still access the camera properly. If the functionality works fine, then I should not set the value of `useSupported` to `false`."

throw error is expected, will not cause application crash.

**Comment by childrentime** [comment]
and pr welcome🥰
