### ISSUE TITLE
Discussion: Should we listen to the reference parameters passed by the user

### ISSUE THREAD

**Issue by childrentime** [childrentime/reactuse#43]
Write a custom hook like this

const referenceObject = {a: 1}
```ts
export default function useMyHook(options: UseMyHookOptions) {
  const {
     someReference  = someOptions
  } = options;

 useEffect(() => {
  // do something
}, [JSON.stringfy(someReference])
}
```

In all honesty, I think this is somewhat pathological. According to the React pattern, shouldn't we allow users to pass immutable references as arguments?

so we can just write like this

```ts
export default function useMyHook(options: UseMyHookOptions) {
  const {
     someReference  = someOptions
  } = options;

 useEffect(() => {
  // do something
}, [someReference)
```

**Comment by childrentime** [comment]
@Daydreamer-riri Hi, do you have any idea of this. I am kind  sick of 
```tsx
  useDeepCompareEffect(() => {

  // reference object
  }, [options]);
```

**Comment by Daydreamer-riri** [comment]
I don't think we need to deal with mutable data, this will cause additional performance consumption, and it is not the default behavior of react, which will cause behavior that is not as expected.

I think we can default the reference unchanged, which means the content remains unchanged

**Comment by childrentime** [comment]
Great. I'll refactor code some day. And declare this constraint into the documentation. Let's make this repository code a little more organized and standardized😍
