### ISSUE TITLE
Discussion: Standardization

### ISSUE THREAD

**Issue by childrentime** [childrentime/reactuse#44]
1. name export instread of export default
2. add params interface and return interface for every single function
3. The type of dom element to be passed?

**Comment by childrentime** [comment]
4. remove the code that check if a component has been umount since https://github.com/reactwg/react-18/discussions/82

**Comment by Daydreamer-riri** [comment]
I've had more time recently and I think I can continue to contribute to the project.

**Comment by childrentime** [comment]
Well, this remains a problem. Some hooks like `useWindowSize`, You can achieve it using either useEffect or useSyncExternalStore. I have no idea to choose which. But you can start to solve the others.

**Comment by childrentime** [comment]
3. The type of dom element to be passed,  The discussion is about which parameters this hook can accept, such as window, document, and refObject.

**Comment by Daydreamer-riri** [comment]
> 3. The type of dom element to be passed,  The discussion is about which parameters this hook can accept, such as window, document, and refObject.

Perhaps we could accept a function that returns a reference to a dom element so that the user can pass the dom in any way.

```ts
type GetElement = () => Element | Window | Document

useSomeHooks({
  getElement: () => domRef.ref,
  // or
  getElement: () => document.querySelector('.some-class'),
  // or
  getElement: () => window,  // This also avoids SSR errors
})
```

We can also refer to some other popular hooks libraries, such as useGesture, framer. 
I will investigate and open an Issue.

**Comment by childrentime** [comment]
we already have `getTargetElement`, I wonder if there's anything uncertain with it

**Comment by childrentime** [comment]
We also need to organize the utils folder

**Comment by Daydreamer-riri** [comment]
I get it, I'll see what I can do.
