### ISSUE TITLE
Use Vite-React-SSG

### ISSUE THREAD

**Issue by Daydreamer-riri** [childrentime/reactuse#50]
Hi, @childrentime , I implemented a library with zero configuration to implement SSR for development and SSG for production, and I think the scenario fits well with our documentation station.

Would you be interested in using it?

[Here](https://github.com/Daydreamer-riri/reactuse/tree/vite-react-ssg) is a version of the documentation that already uses vite-react-ssg.

**Comment by childrentime** [comment]
just make a pr👀
