### ISSUE TITLE
Could not find a declaration file, any version

### ISSUE THREAD

**Issue by milkyfuckinway** [childrentime/reactuse#65]
![image](https://github.com/childrentime/reactuse/assets/106594921/ff75d3b3-b833-451e-bb40-d0c50ab931bc)

**Comment by childrentime** [comment]
@milkyfuckinway sorry. please use latest version 4.0.13. Version 4.0.11 accidently delete types export in "exports" field.

**Comment by childrentime** [comment]
https://publint.dev/@reactuses/core@4.0.13
