### ISSUE TITLE
Documentation: Element target support dropped in v5.0.0

### ISSUE THREAD

**Issue by bfaulk96** [childrentime/reactuse#69]
In the version 5.0.0 release, support for passing in a DOM HTMLElement directly for the `target` param of many hooks (such as `useElementSize`) was dropped in favor of a `ref`. While the current documentation reflects the update correctly for new users of this library, it would be useful to developers trying to update from 4.0.0 -> 5.0.0 if that change was noted in GitHub's [Changelog](https://github.com/childrentime/reactuse/releases/tag/v5.0.0) for that release.

**Comment by childrentime** [comment]
My mistake. I used to think that there were not many people using hooks that directly support the features of DOM, and using ref may be easier for users to understand. Do you think I need to restore these hooks to their previous state?

**Comment by bfaulk96** [comment]
I don't think they need to necessarily be restored, but a note should be made at least in the notes that it was removed.
That being said, a ref isn't always available. My team is now using a fake ref – `{ current: document.getElementById('someElem') }` where we used to use an element

**Comment by childrentime** [comment]
Thanks your reply😘. I will handle it asap.

**Comment by childrentime** [comment]
https://github.com/childrentime/reactuse/blob/main/packages/core/changelog.md#500feb-05-2024.

I've added it in the changelog. I'm very sorry for the trouble caused to you and your team. Next time, if there's a major version with breaking changes, I'll open an issue for discussion first.

Additionally, I will restore these features in version 5.0.7, which will be fully compatible with version 5.0.6 and will not introduce any breaking change
