### ISSUE TITLE
useOnceEffect not executing cleanup function

### ISSUE THREAD

**Issue by Dacaramo** [childrentime/reactuse#79]
OS: Windows 11
Browser: Firefox Developer 125.0b9 (64-bit)
React: 18
Next.js: 14.0.3

useOnceEffect not executing cleanup function is not executing the cleanup function when the component unmounts on Next.js

```TSX
  useOnceEffect(() => {
    console.log('body')
    return () => {
      console.log('cleanup');
    };
  }, []);
```

"cleanup" is never being logged.

"body" is being logged once as it should be, even with Strict Mode enabled

**Comment by childrentime** [comment]
Indeed, I will fix it immediately.

**Comment by childrentime** [comment]
@Dacaramo use 5.0.11
